name: sida
channels:
  - pytorch
  - nvidia
dependencies:
  - python==3.12
  - pip
  - numpy=2.1.3
  - click=8.1.7
  - pillow=11.0.0
  - scipy=1.14.1
  - pytorch=2.4.1
  - psutil=5.9.0
  - requests=2.32.3
  - tqdm=4.66.5
  - imageio=2.9.0
  - pip:
    - imageio-ffmpeg==0.5.1
    - pyspng==0.1.2
    - diffusers==0.32.1
    - accelerate==1.2.1